"""add search_events table

Revision ID: 9039df349c31
Revises: d97ea1c1b2fd
Create Date: 2026-01-08 19:36:47.645848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9039df349c31'
down_revision: Union[str, Sequence[str], None] = 'd97ea1c1b2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'reserve_date',
               existing_type=sa.DATE(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False)
    op.drop_index(op.f('uq_reservations_active_user_book'), table_name='reservations', postgresql_where="((status)::text = 'active'::text)")
    op.add_column('search_events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('search_events', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('search_events', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('search_events', sa.Column('query_text', sa.String(length=511), nullable=True))
    op.add_column('search_events', sa.Column('created_at', sa.Date(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.create_foreign_key(op.f('fk_search_events_author_id_authors'), 'search_events', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_search_events_genre_id_genres'), 'search_events', 'genres', ['genre_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_search_events_user_id_users'), 'search_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_search_events_user_id_users'), 'search_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_search_events_genre_id_genres'), 'search_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_search_events_author_id_authors'), 'search_events', type_='foreignkey')
    op.drop_column('search_events', 'created_at')
    op.drop_column('search_events', 'query_text')
    op.drop_column('search_events', 'author_id')
    op.drop_column('search_events', 'genre_id')
    op.drop_column('search_events', 'user_id')
    op.create_index(op.f('uq_reservations_active_user_book'), 'reservations', ['user_id', 'book_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.alter_column('reservations', 'reserve_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    # ### end Alembic commands ###
