"""full schema - version 0

Revision ID: a17834d9a4a7
Revises: 29b2cadaf3de
Create Date: 2025-11-15 00:09:55.099171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a17834d9a4a7'
down_revision: Union[str, Sequence[str], None] = '29b2cadaf3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reserve_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'returned', 'overdue', name='reservationstatus', native_enum=False), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('authors', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('authors', sa.Column('nationality', sa.String(length=255), nullable=True))
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('authors_name_key'), 'authors', type_='unique')
    op.add_column('books', sa.Column('isbn', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'], ondelete='SET NULL')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('books', 'count')
    op.drop_column('books', 'published_year')
    op.drop_column('books', 'genre_id')
    op.drop_column('books', 'isbn')
    op.create_unique_constraint(op.f('authors_name_key'), 'authors', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('authors', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('authors', 'nationality')
    op.drop_column('authors', 'birthday')
    op.drop_table('reservations')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('genres')
    # ### end Alembic commands ###
